### ISSUE TITLE
Open peering

### ISSUE THREAD

**Issue by lgierth** [hyperboria/bugs#7]
@kpcyrd commented on 25 Dec 2014

> ohai,
> 
> first, I'm well aware that cjdns is a friend to friend network. Anyway, I don't think the current challenge to get into the network (asking on irc) is hard enough to keep advisories outside, but is keeping potential users and devs away who don't want to socially interact until they decided to contribute to the community.
> 
> I've seen the open nodes have been shutdown because they centralize the network, but I propose a different approach.
> 
> Implement a bootstrapping mechanism that would connect to open routers. Those routers publish their public legacy ip and announce that they accept empty connect passwords. This is done via various torrent trackers with a cjdns specific hash. The clients are then able to receive those router addresses and connect to them.
> 
> The reasons I've found to use the connect password are:
> - You want to build a private network that isn't part of hyperboria
> - You don't want everybody to leech your limited traffic
> - Afaik the current implementation doesn't allow probing for cjdns without a valid password
> 
> The tor project has proven that there are relay operators out there who are willing to donate lots of bandwidth and don't worry about it's ip address being exposen.
> 
> This would improve cjdns speed by offering an optional two hop route that might be faster than the existing cjdns network. Also, we might bypass the blackhole routing issue that nobody is working on.
> 
> If you care about resilience or are afraid about malicious routers trying to learn your public ip, you'd create routes like we're doing now.
> 
> If you flag your router as open router you'd expect greater traffic and we have good routes for heavier cjdns usage without crunching all the cheap vpsen out there.
> 
> Both, announcing as an open router and connecting to public routers is opt-in.
> 
> We should consider to
> - Adopt the open net policy
> - Freeze the spec
> - Check if there are major bugs and fix them
> - Get an implementation packaged in distros
> - Get an android app into the stores
> - Get network-manager-cjdns preinstalled on distros
> 
> I think we need hyperboria too much to keep it in semi-public testing any longer. I've talked to a lot of people who didn't want to deploy it because it's too hard for the average user to take advantage of it.

@iShift commented on 2 Jan

> ahh, Open Routers with auto discover and auto configuration, good old idea, but how i know @cjdelisle don't think so.

@atommixz commented on 3 Jan

> I think, we can use DHT trackerless for this.

@kpcyrd commented on 3 Jan

> cjd told me there's been a discussion about this on irc which I've missed. I'm currently semi available on irc since I have flaky routes to the network. Please express your opinion in here if you want me to read it. You can also email me any time if you take the the email address of any of my commits.
> 
> @iShift If I paraphrase somebody (not sure if I'm allowed to quote him on the clearnet) on irc
> - hyperboria is not an anonymous network
> - it's a private one
> - we know who you are
> - but we don't know what you're doing
> 
> It's fun to stick to the strict definition of the term darknet, but I think this is more of a burden instead of an advantage. Social interaction sucks. I think we need to cut this out. It's something the dn42 folks are doing because their technology requires it.
> 
> I am aware that we're reducing the anonymity to the level of torrents, but the pirates out there already figured out how to solve this problem.
> 
> The only reason I haven't started implementing yet, is, because this would open up the network. I'd like to have kind of a consensus decision on this. (oh, one sec, I have an idea)
> 
> @atommixz I'm currently thinking about an approach that'd link to a torrent library (without actually linking it into cjdns, completely sandboxed). Then we'd use whatever works for us.

@kpcyrd commented on 3 Jan

> https://github.com/kpcyrd/consensus-cjdns-opennet

@cschmittiey commented on 3 Jan

> I agree that there's a problem with getting into hyperboria. We want contributors, but the people asking for peers don't know how to contribute, and most people don't want to dive into CJDNS right off the bat, without getting a feel if the work is worth it. And let's be real, testing cjdns locally with only 2-3 peers isn't quite as exciting as Hyperboria, so it's harder to find potential contributors.
> 
> So I think this is a good push, but I also think that we still need to find a way to "know your peers." That's one of Hyperboria's redeeming qualities, is that your peers are usually your friends or acquaintances. There needs to be a better way to know your peers, especially if we're going to use empty connect passwords.

@GratefulTony commented on 3 Jan

> I have been following this project for a long time, and would love to see the network grow. I agree that the current "application process" is limiting the size of the network, but it is also clear to me that the cjdns infrastructure is missing some serious functionality that precludes its use as a general-purpose network. Currently, the routing infrastructure simply doesn't provision much for dealing with abusive peers, and "punts", so to speak, the issue to social reputation. I am not currently on Hyperboria, though I was invited, because I think we shouldn't get too comfortable with the infrastructure as it exists. cjdns needs better QOS management etc. if it will ever be a real, general purpose network! I have long lobbied for bitcoin for bandwidth, or bandwidth for bandwidth to be incorporated at a low level, but I agree that cjdns is still far too "alpha" to worry about that right now... So: don't open Hyperboria until it is ready to deal with all the nasties the real internet can. $0.02

@willeponken commented on 3 Jan

> - Adopt the open net policy - Should be discussed a bit more
> - Freeze the spec - I'm all for this, but I suppose that was already on the roadmap
> - Check if there are major bugs and fix them - Yes
> - Get an implementation packaged in distros - Yes
> - Get an android app into the stores - Atleast a working app with a GUI (is there any?)
> - Get network-manager-cjdns preinstalled on distros - Yes
> 
> All this is in order of priority right? The last one is pretty far fetched :wink:

@wfleurant commented on 4 Jan

> I think this is a great idea. I am going to mark this accordingly here: https://github.com/kpcyrd/consensus-cjdns-opennet
> 
> I could not understand the 'reasons' given why this is not a great idea. Just ping this issue/question off the hypeirc chan if you would like to experience some of these opinions/philosophies for your self.
> 
> We should all be striving for an open-darknet not a closed-darknet.
> 
> Never speculate, only measure.
> Measure twice, cut once.

@ansuz commented on 4 Jan

> I've been working on diagnosing why we're having routing problems, and building tools in nodejs to help gather info. When we run into the black hole routing problem, we need table dumps from both concerned nodes. So far I've been limited to waiting for black holes to pop up between my own nodes, or occasionally getting a bug report from someone else.
> 
> An open net is great in principle, but at this point every unattended node on the net is just another dead end in terms of gathering information for debugging.
> 
> I'd be fine with public peers if:
> - those who used them kept their nodes up to date OR
> - if the public node operator had some way of dropping old nodes AND
> - if those users were also able to offer table dumps or other info.
> 
> So far that hasn't been the case.
> 
> I'd be much more open to arguments premised on methods of adding/removing peers that would address these issues. Ideological arguments aren't getting us anywhere.

@wobbol commented on 5 Jan

> I am with ansus on making it real easy for people to give the project debug information.
> This project desperately needs "field data" feedback on very recent "dev builds"
> I think the best solution would be to have each passwordless client connecting to the open nodes to the verify that they are on the most recent build then proceed with connecting to the network.
> 
> The thing that should be considered most of all IMO is getting the users of the network onboard with keeping their router software up to date
> to convince the masses that it is a good idea to stay up to date the project should:
> - make it easy
> - make it informative(non-trivial change logs)
> - provide examples and implications of not having a homogenous network(past examples, current examples, future examples)
>   - These examples should not even hint at the fear mongering tactics that malware cleaners love to employ.
>   - People get used to those kinds of messages (personally I uninstall software that treats me like I am 5.)

@benhylau commented on 13 Jan

> @willeponken This Android app with UI is happening here WIP
> 
> Would actually like some input from everyone interested

@kpcyrd commented on 13 Jan

> I'm dumping my latest ideas, you're all permitted to call me nuts:
> Allow every application to manage their own peer set
> 
> A config value, on by defaults, that enables an anonymous api to add peers and remove the peers they've added. That'd be incredible useful for applications targeting end users who've never heard about peering. Or irc.
> 
> Every application is able to get the ipv4, ipv6 and cjdns ip anyway, so there's no privacy leak in this one.
> 
> I kinda think this is bad for routing, so we probably need the next one for this.
> Add leaf nodes that don't participate in routing
> 
> Not every device should participate in routing. I'm not sure if this is possible, but it I think this would be good for routing and we can start pushing more traffic because everybody who can't push a lot of traffic probably shouldn't be part of a backbone anyway.
> Hardcode compatible versions
> 
> Hyperboria is the test network but it's not useful for testing if everybody is running a different version. If you're running a version that is too old, you'll automatically drop out of the network.
> Sacrifice pseudonymity for connectivity
> 
> Enable internet autopeering by default. A flag in --genconf disables this behavior. No more social interaction required, yey. If you prefer friend2friend pseudonymity you just enable the flag to disable this and only add peers you trust.
> cjdns.js
> 
> Compile cjdns to javascript and add a websocket transport to run cjdns in the browser (Yes, I am this crazy). That'd allow tor2web-like access to cjdns networks. It's not really secure (it's not trying to be that in the first place), but it'd allow information to be free.
> The vote
> 
> I'm considering forking the network but I don't think routing is going to work if you're connected to two networks bigger than your nodestore. You'd have to choose between network A and network B.
> 
> internet auto-peering and cjdns.js would be the point anybody can access hyperboria without going through the approval process. Excuse my strong opinion but do we really think our adversaries can't "I can haz peer" on irc? Unpeering doesn't work anyway. If you don't believe me, checkout how cjdns upgrade is going.

@iShift commented on 13 Jan

> cjdns.js - bad idea, it is not made for that, cjdns is L2 solution

@kpcyrd commented on 13 Jan

> cjdns.js would be a leaf node that doesn't do routing

@jedahan commented on 13 Jan

> no harm in trying it out
> i thought bittorrent in the webbrowser was c-c-c-crazy until peer5 showed up
> thinking of cjdns.js at the application layer could still be useful

@iShift commented on 13 Jan

> @jedahan bitorrent in webbrowser is webtorrent https://github.com/feross/webtorrent how cjdns at application layer can be useful ?

@kpcyrd commented on 13 Jan

> @iShift cjdns.js is a layer2 over layer7 tunnel, kind of like UDPInterface.c is a layer2 over layer4 tunnel.

@iShift commented on 13 Jan

> @kpcyrd encapsulated... so - no broadcast, no auto-zero-config...

@kpcyrd commented on 14 Jan

> The public peers wiki page appeared again, so I'm taking this as a "go ahead".
> 
> I need some time to actually implement this, help appreciated.
> 
> https://github.com/kpcyrd/yrd

@iShift commented on 14 Jan

> @kpcyrd what is this?

@kpcyrd commented on 14 Jan

> basically cjdcmd-ng-ng. I want to add some extra stuff, like optional public peer discovery and an easier and more unified cjdns deployment.

**Comment by cyisfor** [comment]
If just asking on IRC isn't hard enough to keep out adversaries, then you need to do *more* than ask on IRC, not less. I would suggest presenting yourself on IRC, or a website, explaining why people would want to be your friend, along with your intent to peer. It's still easy to lie about that, but it's a lot easier to lie about one line statements on IRC that amount to "gibbe peers plox."

If you can't keep out adversaries, while you blindly add peers over IRC, then running a node that blindly adds peers automatically and silently in the background isn't going to make you any more secure.

Members of Hyperboria are motivated to go out and make friends, because in addition to having friends they can also increase the amount of trusted participants in the network. People interested in Hyperboria should also be motivated to make friends, and be preferential to friends who are already in Hyperboria, especially if they're well known to be reliable. So there shouldn't be any difficulty getting on the network. Both parties benefit, if they're willing to open up to each other. It's just a little bit different from the usual faceless, friendless "LFP" you've become accustomed to.

The best strategy for people who really don't want to make friends (for some reason) is to purchase a VPS, run cjdns on it, then say in IRC "hey I have a peer with static IP up 24/7 and with bandwidth. Anyone want to peer w/ me?"

I personally think asking on IRC is a terrible idea, but only because that makes us dependent on *EFnet*. EFnet bans privacy, so they make it hard for you to open up to people, since they could potentially attack your computer, or attempt to dox you. But a good idea is asking your neighbors, in person, or asking your local Hackerspace, or asking your local radio club, or asking on a forum, or asking here, and if all that fails I guess you could try IRC. What we really need is a more social presence, such as on social networking sites, other IRC networks, on blogging sites, or things like that. Auto-peering should IMO be confined to direct connections very close geographically, and we don't need to attempt to do so over the shoddy hack they call the conventional Internet.

**Comment by cjdelisle** [comment]
a wild IETF appears

**Comment by Mikaela** [comment]
I personally find it difficult to go on IRC and ask for peers as currently I would only be able to leech as I am not able to put much money on VPS safely and my VPS is OpenVZ which appears to be incompatible with cjdns.

When I first heard of cjdns, I was having burnout and didn't have energy to research it even if I was asked to¸ I somehow only got elitist impression, now later I am more curious on darknets and cdjns and how they could benefit me to break through carrier grade NATs even on networks without native IPv6 (that I have in most of places I actively spend time willingly) and how I understood that I would not need to worry so much about TLS/validation within cjdns and that it could be used for linking IRCds more stably and securely.

However I am root only on one IRCds of our network and even having gotten cjdns to work on my laptop with one public peer I was able to find and not being a coder, I cannot promise that we would start using cjdns and I cannot provide anything of worth to Hyberboria due to not being a coder, so I am not going to ask anyone for peering.

I don't know how many similar experiences there are untold or if everyone else is just more brave in asking for peering. It's probably safe to say that I am good at decreasing my worth and I cannot think of why anyone would want to be my friend without knowing me already and I am not sure how stable basis for a friendship request for peering without giving anything back is.

I apologize in case you find my experience or this comment entirely irrelevant to the topic.

**Comment by ansuz** [comment]
@Mikaela you may be interested in the [public peers repo](https://github.com/hyperboria/peers).
